"""Tests for the XY-chart renderer (VIEWMD-0048).

No upstream reference implementation to differentially test against (like
pie/quadrant, unlike flowchart/sequence/ER) -- termaid's own rendering was
a useful cross-check during design (see the issue's Design notes), not an
oracle, and it uses a different (edge-anchored, two-level) bar rounding
and a diagonal line style. Fixtures in tests/fixtures/mermaid_xychart/ are
hand-authored/generated by this renderer itself and visually verified.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import viewmd.mermaid as mermaid
from viewmd.mermaid.preprocess import MERMAID_RENDERED_INFO, render_mermaid_blocks
from viewmd.mermaid.xychart.parser import parse
from viewmd.mermaid.xychart.renderer import _bar_glyph, _plot_geometry, render
from viewmd.render import render_markdown

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_xychart"


def _inner_plot_width(out: str) -> int:
    widths = []
    for line in out.splitlines():
        if "│" in line:
            widths.append(len(line.split("│", 1)[1]))
        elif "|" in line and not line.strip().startswith("|"):
            # ascii mode
            parts = line.split("|", 1)
            if len(parts) == 2:
                widths.append(len(parts[1]))
    return max(widths) if widths else 0


def _plot_height(out: str) -> int:
    n = 0
    for line in out.splitlines():
        if "│" in line or (
            "|" in line and not line.strip().startswith("|") and "---" not in line
        ):
            n += 1
    return n


def _row_for_tick(out: str, tick: str) -> str:
    for line in out.splitlines():
        if line.lstrip().startswith(tick + " ") or line.lstrip().startswith(tick + " │"):
            if "│" in line:
                return line
    raise AssertionError(f"no row labelled {tick!r} in:\n{out}")


# ---------------------------------------------------------------------------
# Requirement 7: bar glyph formula (row-centered eighth-blocks)
# ---------------------------------------------------------------------------


def test_bar_glyph_precise_sales_examples():
    # Issue mockup: step 10, row V's band is [V-5, V+5).
    assert _bar_glyph(42.5, 40, 10, use_ascii=False) == "▆"
    assert _bar_glyph(67.3, 70, 10, use_ascii=False) == "▂"
    assert _bar_glyph(23.8, 20, 10, use_ascii=False) == "▇"
    assert _bar_glyph(89.1, 90, 10, use_ascii=False) == "▃"


def test_bar_glyph_exact_tick_is_half_block():
    assert _bar_glyph(40, 40, 10, use_ascii=False) == "▄"
    assert _bar_glyph(40, 30, 10, use_ascii=False) == "█"
    assert _bar_glyph(40, 50, 10, use_ascii=False) == " "


def test_bar_glyph_every_eighth():
    # Row V=4, step=1, band [3.5, 4.5). h = 3.5 + k/8 for k=1..8.
    expected = "▁▂▃▄▅▆▇█"
    for k, ch in enumerate(expected, start=1):
        h = 3.5 + k / 8
        assert _bar_glyph(h, 4, 1, use_ascii=False) == ch, (k, h)


def test_bar_glyph_ascii_collapses_to_one_fill():
    assert _bar_glyph(40, 40, 10, use_ascii=True) == "#"
    assert _bar_glyph(40, 30, 10, use_ascii=True) == "#"
    assert _bar_glyph(40, 50, 10, use_ascii=True) == " "


# ---------------------------------------------------------------------------
# Golden fixtures
# ---------------------------------------------------------------------------


def _golden_cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        expected = mmd.with_suffix(".out")
        if expected.exists():
            yield pytest.param(mmd, expected, id=mmd.stem)


@pytest.mark.parametrize("mmd_path,expected_path", list(_golden_cases()))
def test_matches_fixture(mmd_path, expected_path):
    chart = parse(mmd_path.read_text())
    width = 100 if mmd_path.stem == "nvda" else 80
    assert render(chart, use_ascii=False, width=width) == expected_path.read_text()


def test_tick_aligned_bar_renders_half_block():
    # y 0-->10 with W=10 yields n_rows=5, step=2, so 4 is an exact tick.
    chart = parse("xychart-beta\n    x-axis [A]\n    y-axis 0 --> 10\n    bar [4]\n")
    out = render(chart, use_ascii=False, width=10)
    row = _row_for_tick(out, "4")
    assert "▄" in row
    assert "█" not in row.split("│", 1)[1]


def test_eighth_block_levels_all_appear_in_a_render():
    # 8 categories, W=16 -> plot_w=16 (at the 100% cap), n_rows=8, step=1
    # for y 0-->8. Bars land at 3.5+k/8 so row 4 shows every eighth glyph.
    cats = ",".join("ABCDEFGH")
    vals = ",".join(str(3.5 + k / 8) for k in range(1, 9))
    chart = parse(
        f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 8\n    bar [{vals}]\n"
    )
    out = render(chart, use_ascii=False, width=16)
    row = _row_for_tick(out, "4")
    plot = row.split("│", 1)[1]
    for ch in "▁▂▃▄▅▆▇█":
        assert ch in plot, f"missing {ch!r} in {plot!r}\n{out}"


# ---------------------------------------------------------------------------
# Requirement 8: plot area scales with caller-supplied width
# ---------------------------------------------------------------------------


_SALES = (
    "xychart-beta\n"
    '    title "Sales"\n'
    "    x-axis [Q1, Q2, Q3, Q4]\n"
    "    y-axis 0 --> 100\n"
    "    bar [40, 55, 70, 90]\n"
)


def test_plot_width_at_fifty_percent_floor():
    # 4 short categories: content min is well below 50% of W=80, so the
    # plot sits on the floor (40 columns) with height close to width (1:1).
    chart = parse(_SALES)
    out = render(chart, use_ascii=False, width=80)
    pw = _inner_plot_width(out)
    ph = _plot_height(out)
    assert pw == 40
    assert ph == 40
    # Must not compress narrower than the floor.
    assert pw >= 40


def test_plot_width_at_one_hundred_percent_cap():
    # 10 one-char categories, content min 20. W=20 puts the plot on the
    # 100% ceiling; it must not grow past it.
    cats = ",".join(f"{i}" for i in range(10))
    vals = ",".join("1" for _ in range(10))
    chart = parse(f"xychart-beta\n    x-axis [{cats}]\n    bar [{vals}]\n")
    out = render(chart, use_ascii=False, width=20)
    pw = _inner_plot_width(out)
    ph = _plot_height(out)
    assert pw == 20
    assert ph == 10  # 2:1 at the ceiling
    assert pw <= 20


def test_plot_height_grows_slower_than_width_between_bounds():
    # W=30, 10 one-char cats, content=20: between floor 15 and ceil 30.
    cats = ",".join(f"{i}" for i in range(10))
    vals = ",".join("1" for _ in range(10))
    chart = parse(f"xychart-beta\n    x-axis [{cats}]\n    bar [{vals}]\n")
    out = render(chart, use_ascii=False, width=30)
    pw = _inner_plot_width(out)
    ph = _plot_height(out)
    assert pw == 20
    assert ph == 15  # frozen at the 50%-of-W floor, so height < width
    assert pw / ph <= 2.0 + 1e-9


def test_plot_overflows_when_fifty_percent_floor_cannot_fit_labels():
    # 10 long labels, min_col ~ 10, content ~ 100. W=20 cannot hold them
    # even at 100%, so the plot overflows and scrolls (VIEWMD-0018).
    cats = ",".join(f"Category{i}" for i in range(10))
    vals = ",".join("1" for _ in range(10))
    chart = parse(f"xychart-beta\n    x-axis [{cats}]\n    bar [{vals}]\n")
    out = render(chart, use_ascii=False, width=20)
    pw = _inner_plot_width(out)
    assert pw > 20


def test_plot_geometry_unit():
    # Directly pins the three requirement-8 bounds.
    col, pw, rows = _plot_geometry(4, 3, 80)
    assert pw == 40 and rows == 40 and col == 10
    col, pw, rows = _plot_geometry(10, 2, 20)
    assert pw == 20 and rows == 10 and col == 2
    col, pw, rows = _plot_geometry(10, 2, 30)
    assert pw == 20 and rows == 15 and col == 2
    # Snapping to whole columns must not drop back below the 50% floor.
    col, pw, rows = _plot_geometry(13, 6, 200)
    assert pw >= 100
    assert pw <= 200


def test_cli_width_reaches_the_renderer():
    # Same plumbing regression pie/quadrant already pin: `width` must not
    # be dropped in favour of a freshly-queried terminal size.
    md = f"```mermaid\n{_SALES}```\n"
    narrow = render_markdown(md, width=40, color=False)
    wide = render_markdown(md, width=80, color=False)
    assert narrow != wide


# ---------------------------------------------------------------------------
# use_ascii fallback (requirement 7)
# ---------------------------------------------------------------------------


def test_ascii_mode_collapses_bar_and_line_glyphs():
    chart = parse(
        "xychart-beta\n"
        "    x-axis [Q1, Q2, Q3, Q4]\n"
        "    y-axis 0 --> 100\n"
        "    bar  [40, 60, 80, 100]\n"
        "    line [60, 80, 100, 120]\n"
    )
    out = render(chart, use_ascii=True, width=80)
    for ch in "█▁▂▃▄▅▆▇╭╮╰╯│─└┬":
        assert ch not in out
    assert "#" in out
    assert "+" in out
    assert "-" in out
    assert "|" in out


# ---------------------------------------------------------------------------
# Dispatch / fallback (requirement 9 and unsupported multi-series)
# ---------------------------------------------------------------------------


def test_xychart_fence_is_recognized_end_to_end():
    text = "```mermaid\n" + _SALES + "```\n"
    got = render_mermaid_blocks(text, width=80)
    assert "```mermaid\n" not in got
    assert f"```{MERMAID_RENDERED_INFO}\n" in got
    assert "Sales" in got
    assert "│" in got


def test_bare_xychart_fence_is_recognized_end_to_end():
    text = "```mermaid\nxychart\n    x-axis [A, B]\n    bar [1, 2]\n```\n"
    got = render_mermaid_blocks(text, width=80)
    assert f"```{MERMAID_RENDERED_INFO}\n" in got


def test_malformed_dataset_length_falls_back_to_raw_fence():
    text = "```mermaid\nxychart-beta\n    x-axis [A, B, C]\n    bar [1, 2]\n```\n"
    assert render_mermaid_blocks(text) == text
    with pytest.raises(mermaid.MermaidError):
        mermaid.render("xychart-beta\n    x-axis [A, B, C]\n    bar [1, 2]\n")


def test_multi_series_falls_back_to_raw_fence():
    text = (
        "```mermaid\n"
        "xychart\n"
        '    title "Different Colors in xyChart"\n'
        '    x-axis "categoriesX" ["Category 1", "Category 2", "Category 3", "Category 4"]\n'
        '    y-axis "valuesY" 0 --> 50\n'
        "    line [10,20,30,40]\n"
        "    bar [20,30,25,35]\n"
        "    bar [15,25,20,30]\n"
        "    line [5,15,25,35]\n"
        "```\n"
    )
    assert render_mermaid_blocks(text) == text


def test_numeric_x_axis_falls_back_to_raw_fence():
    text = "```mermaid\nxychart-beta\n    x-axis 0 --> 10\n    bar [1, 2]\n```\n"
    assert render_mermaid_blocks(text) == text


def test_horizontal_still_renders_bottom_up():
    src = (
        "xychart-beta horizontal\n"
        "    x-axis [Q1, Q2]\n"
        "    y-axis 0 --> 10\n"
        "    bar [4, 8]\n"
    )
    out = render(parse(src), use_ascii=False, width=20)
    # Categories along the bottom, not down the left edge.
    assert out.splitlines()[-1].strip().startswith("Q1")
    assert "Q2" in out.splitlines()[-1]


def test_auto_scale_uses_data_min_max():
    chart = parse("xychart-beta\n    x-axis [A, B]\n    bar [40, 80]\n")
    out = render(chart, use_ascii=False, width=20)
    # Top tick is the data max (or close); bottom is the data min.
    ticks = [ln.split()[0] for ln in out.splitlines() if "│" in ln or "└" in ln]
    assert "80" in ticks[0]
    assert "40" in ticks[-1]


def test_existing_diagram_types_unchanged():
    # Requirement 10: a pie fence still renders as a pie, not an xychart.
    text = '```mermaid\npie\n    "A" : 1\n    "B" : 1\n```\n'
    got = render_mermaid_blocks(text)
    assert "┃" in got
    assert "xychart" not in got
