"""Golden-file regression tests for the entity-relationship-diagram port
(VIEWMD-0016).

Fixtures in tests/fixtures/mermaid_er/ were generated by running each
`<name>.mmd` through the upstream Go reference implementation
(github.com/AlexanderGrooff/mermaid-ascii, MIT licensed) with and without
`--ascii`, saving its stdout as `<name>.unicode.out` / `<name>.ascii.out`. They
pin this port's output to the real Mermaid renderer's, byte for byte.
"""

from pathlib import Path

import pytest

from viewmd.mermaid.er.charset import ASCII, UNICODE
from viewmd.mermaid.er.parser import parse
from viewmd.mermaid.er.renderer import render

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_er"


def _cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        for variant, use_ascii in (("unicode", False), ("ascii", True)):
            expected = mmd.with_name(f"{mmd.stem}.{variant}.out")
            if expected.exists():
                yield pytest.param(mmd, expected, use_ascii, id=f"{mmd.stem}-{variant}")


@pytest.mark.parametrize("mmd_path,expected_path,use_ascii", list(_cases()))
def test_matches_reference_implementation(mmd_path, expected_path, use_ascii):
    d = parse(mmd_path.read_text())
    assert render(d, use_ascii=use_ascii) == expected_path.read_text()


def test_dashed_relationship_glyphs_are_broadly_renderable():
    """VIEWMD-0030: UNICODE.hd/vd must not be the box-drawing glyphs
    (U+2508/U+250A) most monospace terminal fonts lack coverage for."""
    assert UNICODE.hd == "·"  # MIDDLE DOT
    assert UNICODE.vd == ":"  # COLON
    assert ASCII.hd == "."
    assert ASCII.vd == ":"
