"""Golden-file regression tests for the sequence-diagram port (VIEWMD mermaid).

Fixtures in tests/fixtures/mermaid_sequence/ were generated by running each
`<name>.mmd` through the upstream Go reference implementation
(github.com/AlexanderGrooff/mermaid-ascii, MIT licensed) with and without
`--ascii`, saving its stdout as `<name>.unicode.out` / `<name>.ascii.out`. They
pin this port's output to the real Mermaid renderer's, byte for byte.
"""

from pathlib import Path

import pytest

from viewmd.mermaid.sequence.parser import parse
from viewmd.mermaid.sequence.renderer import render

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_sequence"


def _cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        for variant, use_ascii in (("unicode", False), ("ascii", True)):
            expected = mmd.with_name(f"{mmd.stem}.{variant}.out")
            if expected.exists():
                yield pytest.param(mmd, expected, use_ascii, id=f"{mmd.stem}-{variant}")


@pytest.mark.parametrize("mmd_path,expected_path,use_ascii", list(_cases()))
def test_matches_reference_implementation(mmd_path, expected_path, use_ascii):
    sd = parse(mmd_path.read_text())
    assert render(sd, use_ascii=use_ascii) == expected_path.read_text()
