"""Tests for the packet-diagram renderer (VIEWMD-0049).

No upstream reference implementation to differentially test against
(mermaid-ascii has no packet-diagram support, and real Mermaid renders to
SVG, not a terminal grid) -- fixtures in tests/fixtures/mermaid_packet/ are
hand-authored/generated by this renderer itself and visually verified, same
posture as the pie-chart port's VIEWMD-0043 fixtures. The row-wrapping/split
and contiguity-validation logic was checked directly against Mermaid's own
parser/renderer source (see the issue's Design notes and Requirements 2/3),
but exact character-grid proportions have no oracle to match.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from viewmd.mermaid.packet.parser import parse
from viewmd.mermaid.packet.renderer import render

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_packet"


def _cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        for variant, use_ascii in (("unicode", False), ("ascii", True)):
            expected = mmd.with_name(f"{mmd.stem}.{variant}.out")
            if expected.exists():
                yield pytest.param(mmd, expected, use_ascii, id=f"{mmd.stem}-{variant}")


@pytest.mark.parametrize("mmd_path,expected_path,use_ascii", list(_cases()))
def test_matches_fixture(mmd_path, expected_path, use_ascii):
    d = parse(mmd_path.read_text())
    assert render(d, use_ascii=use_ascii) == expected_path.read_text()


def test_empty_diagram_with_no_title_renders_empty_string():
    d = parse("packet-beta")
    assert render(d) == ""


def test_empty_diagram_with_title_renders_title_only():
    d = parse("packet-beta\n    title Just a title")
    assert render(d) == "Just a title"


def test_field_spanning_row_boundary_splits_with_same_label_on_both_rows():
    d = parse(
        'packet-beta\n0-18: "Flags"\n19-47: "Sequence Number"\n48-63: "Checksum"'
    )
    out = render(d)
    lines = out.splitlines()
    assert out.count("Sequence Number") == 2
    # First row's header shows the local 19-31 range, second row's shows 32-47.
    assert "19" in lines[0] and "31" in lines[0]
    assert "32" in lines[4] and "47" in lines[4]


def test_row_flushes_immediately_when_a_field_ends_exactly_on_the_boundary():
    # A single 32-bit field filling exactly one row must not spill an empty
    # continuation onto the next row.
    d = parse('packet-beta\n0-31: "Whole row"')
    out = render(d)
    assert len(out.splitlines()) == 4  # header + top + content + bottom, one row only


def test_title_rendered_centered_above_diagram():
    d = parse('packet-beta\n    title My Title\n0-31: "A"')
    out = render(d)
    lines = out.splitlines()
    assert lines[0].strip() == "My Title"
    # Centered: leading whitespace is about half the gap between the title
    # and the diagram's full width (no trailing padding -- nothing follows
    # the title on its own line, so there's nothing to pad for).
    diagram_width = max(len(line) for line in lines[1:])
    lead = len(lines[0]) - len(lines[0].lstrip(" "))
    assert abs(lead - (diagram_width - len("My Title")) // 2) <= 1


def test_wide_char_label_truncates_without_destroying_borders():
    d = parse('packet-beta\n0: "旗标示例文字"\n1-31: "Rest"')
    out = render(d)
    for line in out.splitlines()[1:]:
        assert line.strip().startswith(("╭", "│", "╰"))
        assert line.strip().endswith(("╮", "│", "╯"))


def test_ascii_mode_uses_no_unicode_box_drawing():
    d = parse('packet-beta\n0-31: "A"')
    out = render(d, use_ascii=True)
    assert "╭" not in out and "│" not in out and "╰" not in out
    assert "+" in out and "-" in out
