"""Tests for the quadrant-chart renderer (VIEWMD-0047).

No upstream reference implementation to differentially test against (like
pie, unlike flowchart/sequence/ER) -- termaid's own free-floating axis-cross
rendering was a useful cross-check during design (see the issue's Design
notes), not an oracle, and it renders a different (borderless) layout. The
plain-box fixture in tests/fixtures/mermaid_quadrant/ is hand-authored/
generated by this renderer itself and visually verified, same posture as the
pie chart's own bar-chart fixtures. Colored rendering embeds real ANSI
escapes whose exact byte layout isn't pinned -- tested for the structural
properties the issue's Acceptance section calls for instead (per-quadrant
tint/background, a point's explicit color overriding its quadrant's
fallback, and color being strictly additive over the plain layout).
"""

from __future__ import annotations

import re
from pathlib import Path

from viewmd.mermaid.quadrant.parser import parse
from viewmd.mermaid.quadrant.renderer import _default_box_width, render
from viewmd.mermaid.textutil import width as string_width

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_quadrant"

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _strip_ansi(s: str) -> str:
    return _ANSI_RE.sub("", s)


# ---------------------------------------------------------------------------
# Plain box: golden fixture (requirement 6)
# ---------------------------------------------------------------------------


def test_priority_matrix_matches_fixture():
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out = render(chart, use_ascii=False, color=False, width=68)
    assert out == (FIXTURES / "priority_matrix.out").read_text()


def test_plain_box_has_no_ansi_when_color_disabled():
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out = render(chart, use_ascii=False, color=False, width=68)
    assert _ANSI_RE.search(out) is None


def test_ascii_mode_uses_plus_and_dash_border():
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out = render(chart, use_ascii=True, color=False, width=68)
    assert "┌" not in out
    assert "+" in out and "-" in out
    assert "●" not in out and "*" in out


# ---------------------------------------------------------------------------
# Collision handling (requirement 9 / Non-goals)
# ---------------------------------------------------------------------------


def test_two_close_points_render_without_crashing():
    chart = parse((FIXTURES / "collision.mmd").read_text())
    out = render(chart, use_ascii=False, color=False, width=68)
    plain = _strip_ansi(out)
    assert "Alpha" in plain
    assert "Beta" in plain


# ---------------------------------------------------------------------------
# Fallback (requirement 8: malformed fence -> caught by viewmd/mermaid/__init__.py,
# not this module directly -- see tests/test_mermaid_preprocess.py's dispatch
# coverage for parser.ParseError -> MermaidError)
# ---------------------------------------------------------------------------


def test_empty_points_still_renders_quadrant_labels_and_axes():
    chart = parse("quadrantChart\ntitle T\nx-axis Lo --> Hi\ny-axis Lo --> Hi\n"
                  "quadrant-1 A\nquadrant-2 B\nquadrant-3 C\nquadrant-4 D\n")
    out = render(chart, use_ascii=False, color=False, width=68)
    for text in ("T", "Lo", "Hi", "A", "B", "C", "D"):
        assert text in out


# ---------------------------------------------------------------------------
# Color (requirement 8)
# ---------------------------------------------------------------------------


def test_color_disabled_is_byte_for_byte_identical_to_plain():
    # Requirement 8's own framing: color is strictly additive, never a
    # different layout.
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    plain = render(chart, use_ascii=False, color=False, width=68)
    colored_stripped = _strip_ansi(render(chart, use_ascii=False, color=True, width=68))
    assert plain == colored_stripped


def test_color_uses_one_fg_tint_per_quadrant_with_points_present():
    # Requirement 8a: each quadrant's border/label/point picks up that
    # quadrant's own hue -- Priority Matrix has all 4 quadrant labels and one
    # point in 2 of them, but every quadrant's border still renders.
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out = render(chart, use_ascii=False, color=True, width=68)
    fg_colors = set(re.findall(r"38;2;(\d+;\d+;\d+)", out))
    assert len(fg_colors) == 4


def test_color_has_one_bg_tint_per_quadrant():
    # Requirement 8b: a solid, darkened background fill covers each
    # quadrant's whole interior.
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out = render(chart, use_ascii=False, color=True, width=68)
    bg_colors = set(re.findall(r"48;2;(\d+;\d+;\d+)", out))
    assert len(bg_colors) == 4


_TRUE_COLOR_RE = re.compile(r"\x1b\[[034]8;2;[0-9;]*m")


def test_title_and_axis_labels_stay_uncolored():
    # Requirement 8d: no true-color (fg/bg) escape on the title or axis-label
    # rows -- the title MAY still be bold (matching the other Mermaid
    # renderers' title treatment), bold is a weight, not a color.
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out = render(chart, use_ascii=False, color=True, width=68)
    lines = out.splitlines()
    title_line = lines[0]
    xaxis_line = lines[-1]
    assert _TRUE_COLOR_RE.search(title_line) is None
    assert _TRUE_COLOR_RE.search(xaxis_line) is None
    assert "Priority Matrix" in _strip_ansi(title_line)
    plain_xaxis = _strip_ansi(xaxis_line)
    assert "Low Effort" in plain_xaxis and "High Effort" in plain_xaxis


def test_mockup_1a_quadrant_fg_and_bg_hex_values():
    # Pins the exact per-quadrant fg/bg hex values from the issue's mockup
    # 1a legend table against example.mmd, the same source that table
    # documents (Acceptance section: "a colored fixture reproducing mockup
    # 1a above... against example.mmd").
    chart = parse((FIXTURES / "example.mmd").read_text())
    out = render(chart, use_ascii=False, color=True, width=100)
    expected = {
        1: ("111;159;216", "31;44;60"),    # We should expand:  #6f9fd8 / #1f2c3c
        2: ("216;138;63", "60;38;17"),     # Need to promote:   #d88a3f / #3c2611
        3: ("63;166;106", "17;46;29"),     # Re-evaluate:       #3fa66a / #112e1d
        4: ("176;111;216", "49;31;60"),    # May be improved:   #b06fd8 / #311f3c
    }
    for fg, bg in expected.values():
        assert f"38;2;{fg}" in out
        assert f"48;2;{bg}" in out


def test_example_styled_fixture_explicit_point_colors_take_effect():
    # Acceptance section: "a second colored fixture against a source with an
    # explicit per-point color: and a :::class -> classDef color: reference
    # (mirroring poc/quadrant/example-styled.mmd), confirming requirement
    # 8c's override actually takes effect."
    chart = parse((FIXTURES / "example-styled.mmd").read_text())
    colors = {p.label: p.color for p in chart.points}
    assert colors["Campaign B"] == "#ff3300"          # own color: style
    assert colors["Campaign C"] == "#00ff33"           # own color: style
    assert colors["Campaign E"] == "#908342"           # classDef color, via :::class2
    assert colors["Campaign A"] is None                # no color/class at all

    out = render(chart, use_ascii=False, color=True, width=100)
    assert "38;2;255;51;0" in out    # Campaign B: #ff3300
    assert "38;2;0;255;51" in out    # Campaign C: #00ff33
    assert "38;2;144;131;66" in out  # Campaign E: #908342 (via classDef)


def test_point_explicit_color_overrides_quadrant_fallback():
    # Requirement 8c.
    chart = parse(
        "quadrantChart\nx-axis Low --> High\ny-axis Low --> High\n"
        "quadrant-1 Q1\nquadrant-2 Q2\nquadrant-3 Q3\nquadrant-4 Q4\n"
        "Styled: [0.9, 0.9] color: #ff3300\n"
        "Unstyled: [0.1, 0.1]\n"
    )
    out = render(chart, use_ascii=False, color=True, width=68)
    assert "38;2;255;51;0" in out  # #ff3300


def test_point_without_explicit_color_falls_back_to_quadrant_tint():
    chart = parse(
        "quadrantChart\nx-axis Low --> High\ny-axis Low --> High\n"
        "quadrant-1 Q1\nquadrant-2 Q2\nquadrant-3 Q3\nquadrant-4 Q4\n"
        "Unstyled: [0.9, 0.9]\n"
    )
    out = render(chart, use_ascii=False, color=True, width=68)
    fg_colors = set(re.findall(r"38;2;(\d+;\d+;\d+)", out))
    # No explicit color anywhere in the source -- every fg color present must
    # be one of the 4 quadrant tints, not a fifth/unrelated color.
    assert len(fg_colors) <= 4


# ---------------------------------------------------------------------------
# Dynamic sizing (requirement 7)
# ---------------------------------------------------------------------------


def test_render_width_kwarg_overrides_raw_terminal_size():
    # Regression shape mirroring VIEWMD-0043's own pie-chart bug: `width`
    # must reach the renderer, not be re-queried from the terminal directly.
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    out_narrow = render(chart, use_ascii=False, color=False, width=60)
    out_wide = render(chart, use_ascii=False, color=False, width=200)
    assert out_narrow != out_wide
    widest_narrow = max(len(line) for line in out_narrow.splitlines())
    widest_wide = max(len(line) for line in out_wide.splitlines())
    assert widest_narrow < widest_wide


def test_default_box_width_scales_with_target_width():
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    assert _default_box_width(chart, 60) < _default_box_width(chart, 100) < \
        _default_box_width(chart, 200)


def test_default_box_width_floors_at_minimum_for_very_narrow_target():
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())
    assert _default_box_width(chart, 1) >= 10


def test_default_box_width_grows_to_fit_a_long_title():
    # Regression: the title used to be ignored by the sizing math entirely
    # (only y-axis label length was considered), so a title longer than the
    # width-derived box would silently overflow past target_width even
    # though requirement 7 names the title explicitly as something the box
    # must fit.
    chart = parse(
        "quadrantChart\n"
        "title This Is A Deliberately Very Long Title For A Narrow Render Width\n"
        "x-axis Lo --> Hi\ny-axis Lo --> Hi\n"
    )
    narrow_target = 40
    qw = _default_box_width(chart, narrow_target)
    box_width = qw * 2 + 3
    assert box_width >= string_width(chart.title)


def test_title_line_does_not_overflow_when_it_fits_the_box():
    chart = parse((FIXTURES / "priority_matrix.mmd").read_text())  # short title
    out = render(chart, use_ascii=False, color=False, width=68)
    title_line = out.splitlines()[0]
    other_line = out.splitlines()[2]  # a border row, box_width + left_pad
    assert len(title_line) == len(other_line)
