"""Tests for the pie-chart renderer (VIEWMD-0043).

No upstream reference implementation to differentially test against (unlike
flowchart/sequence/ER, ported from mermaid-ascii) -- termaid's own bar-chart
rendering was a useful cross-check during design (see the issue's Design
notes), not an oracle, and it has no circular rendering at all. Fixtures in
tests/fixtures/mermaid_pie/ are hand-authored/generated by this renderer
itself and visually verified, same posture as the flowchart port's
VIEWMD-0022-era shape fixtures.

The bar-chart fallback (no color, or --ascii) is deterministic and tested
byte-for-byte against golden fixtures. The circular rendering embeds real
ANSI escapes whose exact byte layout isn't a meaningful thing to pin -- it's
tested for the structural properties VIEWMD-0043's Acceptance section calls
for instead (color/glyph diversity, label placement, no leaked ANSI when
disabled).
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from viewmd.mermaid.pie.parser import parse
from viewmd.mermaid.pie.renderer import (
    _QUADRANT_GLYPH,
    _default_radius,
    render,
)

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_pie"

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _strip_ansi(s: str) -> str:
    return _ANSI_RE.sub("", s)


# ---------------------------------------------------------------------------
# Bar-chart fallback: golden fixtures
# ---------------------------------------------------------------------------


def _bar_cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        for variant, use_ascii in (("bar", False), ("bar-ascii", True)):
            expected = mmd.with_name(f"{mmd.stem}.{variant}.out")
            if expected.exists():
                yield pytest.param(mmd, expected, use_ascii, id=f"{mmd.stem}-{variant}")


@pytest.mark.parametrize("mmd_path,expected_path,use_ascii", list(_bar_cases()))
def test_bar_chart_matches_fixture(mmd_path, expected_path, use_ascii):
    chart = parse(mmd_path.read_text())
    assert render(chart, use_ascii=use_ascii, color=False) == expected_path.read_text()


def test_bar_chart_has_no_ansi_when_color_disabled():
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=False)
    assert _ANSI_RE.search(out) is None


def test_bar_chart_title_bold_when_color_enabled_but_ascii_forced():
    # --color always --ascii: still no circular rendering, but the title is
    # still bold -- bold is gated by color, not by use_ascii.
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=True, color=True)
    assert out.splitlines()[0] == "\x1b[1mPets adopted by volunteers\x1b[0m"
    assert "#" in out  # ascii-safe bar glyph, not the unicode block


def test_empty_pie_bar_chart_renders_title_only():
    chart = parse("pie title Just a title")
    out = render(chart, use_ascii=False, color=False)
    assert out == "Just a title"


def test_empty_pie_no_title_renders_empty_string():
    chart = parse("pie")
    assert render(chart, use_ascii=False, color=False) == ""


# ---------------------------------------------------------------------------
# Circular rendering: structural properties (requirement 4, 4a, 6, 6a, 7)
# ---------------------------------------------------------------------------


def test_circular_uses_exactly_one_ansi_color_per_slice():
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=True)
    colors = set(re.findall(r"38;2;(\d+;\d+;\d+)", out))
    assert len(colors) == len(chart.slices) == 3


def test_circular_has_no_background_ansi():
    # Requirement 4a's quadrant blocks are a pure foreground technique --
    # no fg/bg two-tone split needed, unlike the rejected interior-boundary
    # triangle variant (see Design notes).
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=True)
    assert re.search(r"48;2;\d+;\d+;\d+", out) is None


def test_circular_uses_more_than_one_quadrant_glyph():
    # Guards against silently regressing to a plain full-block-only fill
    # (the second rejected silhouette design) without a test noticing.
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=True)
    plain = _strip_ansi(out)
    partial_glyphs = set(_QUADRANT_GLYPH.values()) - {" ", "█"}
    assert any(g in plain for g in partial_glyphs)


def test_circular_thin_wedge_label_renders_outside_circle():
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=True)
    plain = _strip_ansi(out)
    assert "3%" in plain  # Rats, ~11 degree span, pushed outside per requirement 6
    assert "17%" in plain  # Cats, inside its own wedge
    assert "79%" in plain  # Dogs, inside its own wedge


def test_circular_title_is_bold():
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=True)
    assert "\x1b[1mPets adopted by volunteers\x1b[0m" in out


def test_circular_exactly_one_blank_row_after_title():
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out = render(chart, use_ascii=False, color=True)
    lines = _strip_ansi(out).splitlines()
    assert lines[1] == ""
    assert lines[2].strip() != ""


def test_circular_no_wasted_blank_rows_without_a_thin_wedge():
    chart = parse('pie title Even split\n"A":50\n"B":50')
    out = render(chart, use_ascii=False, color=True)
    lines = _strip_ansi(out).splitlines()
    assert lines[1] == ""
    assert lines[2].strip() != ""


def test_circular_wedge_angle_uses_aspect_corrected_coordinates(monkeypatch):
    # If the angle test ignored `aspect` (used raw dx/dy instead of the
    # aspect-corrected nx/ny), rendering the same chart at two different
    # aspect values would not shift where a slice boundary lands -- this
    # would stay silent without a test checking it (requirement 5).
    import viewmd.mermaid.pie.renderer as renderer_mod

    chart = parse('pie title T\n"A":50\n"B":50')
    monkeypatch.setenv("VIEWMD_PIE_RADIUS", "16")

    monkeypatch.setattr(renderer_mod, "_aspect", lambda: 0.3)
    out_a = _strip_ansi(render(chart, use_ascii=False, color=True))
    monkeypatch.setattr(renderer_mod, "_aspect", lambda: 0.6)
    out_b = _strip_ansi(render(chart, use_ascii=False, color=True))

    assert out_a != out_b


def test_circular_aspect_env_var_changes_row_count(monkeypatch):
    chart = parse((FIXTURES / "pets.mmd").read_text())
    monkeypatch.setenv("VIEWMD_PIE_RADIUS", "20")
    monkeypatch.setenv("VIEWMD_PIE_ASPECT", "0.3")
    out_low = render(chart, use_ascii=False, color=True)
    monkeypatch.setenv("VIEWMD_PIE_ASPECT", "0.6")
    out_high = render(chart, use_ascii=False, color=True)
    assert len(out_low.splitlines()) != len(out_high.splitlines())


def test_circular_radius_env_var_overrides_default(monkeypatch):
    chart = parse((FIXTURES / "pets.mmd").read_text())
    monkeypatch.setenv("VIEWMD_PIE_RADIUS", "10")
    out_small = render(chart, use_ascii=False, color=True)
    monkeypatch.setenv("VIEWMD_PIE_RADIUS", "30")
    out_large = render(chart, use_ascii=False, color=True)
    widest_small = max(len(line) for line in _strip_ansi(out_small).splitlines())
    widest_large = max(len(line) for line in _strip_ansi(out_large).splitlines())
    assert widest_large > widest_small


def test_render_width_kwarg_overrides_raw_terminal_size():
    # Regression: render()'s `width` kwarg used to be silently dropped --
    # the circular renderer queried the raw terminal size directly instead,
    # so --width had no effect at all on the pie's size.
    chart = parse((FIXTURES / "pets.mmd").read_text())
    out_narrow = render(chart, use_ascii=False, color=True, width=60)
    out_wide = render(chart, use_ascii=False, color=True, width=200)
    assert out_narrow != out_wide
    widest_narrow = max(len(line) for line in _strip_ansi(out_narrow).splitlines())
    widest_wide = max(len(line) for line in _strip_ansi(out_wide).splitlines())
    assert widest_narrow < widest_wide


def test_default_radius_scales_with_terminal_width():
    chart = parse((FIXTURES / "pets.mmd").read_text())
    # The maintainer-validated relationship for this exact reference example.
    assert _default_radius(chart, 100) == 24
    assert _default_radius(chart, 80) < _default_radius(chart, 100) < _default_radius(chart, 120)


def test_thin_wedge_label_stays_on_grid_at_large_radius(monkeypatch):
    # Regression: at a large enough radius, a thin outside-pushed label's
    # computed position used to land outside the grid entirely and vanish
    # silently (found by actually rendering at the terminal-derived default
    # radius, not by inspection) -- confirm the fix (clamping) holds.
    chart = parse((FIXTURES / "pets.mmd").read_text())
    monkeypatch.setenv("VIEWMD_PIE_RADIUS", "24")
    out = _strip_ansi(render(chart, use_ascii=False, color=True))
    assert "3%" in out
