"""Tests for the XY-chart renderer (VIEWMD-0048).

No upstream reference implementation to differentially test against (like
pie/quadrant, unlike flowchart/sequence/ER) -- termaid's own rendering was
a useful cross-check during design (see the issue's Design notes), not an
oracle, and it uses a different (edge-anchored, two-level) bar rounding
and a diagonal line style. Fixtures in tests/fixtures/mermaid_xychart/ are
hand-authored/generated by this renderer itself and visually verified.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

import viewmd.mermaid as mermaid
from viewmd.mermaid.preprocess import MERMAID_RENDERED_INFO, render_mermaid_blocks
from viewmd.mermaid.xychart.parser import parse
from viewmd.mermaid.xychart.renderer import (
    _BAR_COLORS,
    _BAR_GAP,
    _LINE_COLOR,
    _UNICODE,
    _bar_color,
    _bar_glyph,
    _build_line_grid,
    _nice_step,
    _plot_color_spans,
    _plot_geometry,
    _snap_to_row,
    render,
)
from viewmd.render import render_markdown

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_xychart"

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _strip_ansi(s: str) -> str:
    return _ANSI_RE.sub("", s)


def _sgr(hex_: str) -> str:
    r, g, b = int(hex_[0:2], 16), int(hex_[2:4], 16), int(hex_[4:6], 16)
    return f"38;2;{r};{g};{b}"


def _bg_sgr(hex_: str) -> str:
    r, g, b = int(hex_[0:2], 16), int(hex_[2:4], 16), int(hex_[4:6], 16)
    return f"48;2;{r};{g};{b}"


def _inner_plot_width(out: str) -> int:
    widths = []
    for line in out.splitlines():
        if "│" in line:
            widths.append(len(line.split("│", 1)[1]))
        elif "|" in line and not line.strip().startswith("|"):
            # ascii mode
            parts = line.split("|", 1)
            if len(parts) == 2:
                widths.append(len(parts[1]))
    return max(widths) if widths else 0


def _plot_height(out: str) -> int:
    n = 0
    for line in out.splitlines():
        if "│" in line or (
            "|" in line and not line.strip().startswith("|") and "---" not in line
        ):
            n += 1
    return n


def _row_for_tick(out: str, tick: str) -> str:
    for line in out.splitlines():
        if line.lstrip().startswith(tick + " ") or line.lstrip().startswith(tick + " │"):
            if "│" in line:
                return line
    raise AssertionError(f"no row labelled {tick!r} in:\n{out}")


# ---------------------------------------------------------------------------
# Requirement 7: bar glyph formula (row-centered eighth-blocks)
# ---------------------------------------------------------------------------


def test_bar_glyph_precise_sales_examples():
    # Issue mockup: step 10, row V's band is [V-5, V+5).
    assert _bar_glyph(42.5, 40, 10, use_ascii=False) == "▆"
    assert _bar_glyph(67.3, 70, 10, use_ascii=False) == "▂"
    assert _bar_glyph(23.8, 20, 10, use_ascii=False) == "▇"
    assert _bar_glyph(89.1, 90, 10, use_ascii=False) == "▃"


def test_bar_glyph_exact_tick_is_half_block():
    assert _bar_glyph(40, 40, 10, use_ascii=False) == "▄"
    assert _bar_glyph(40, 30, 10, use_ascii=False) == "█"
    assert _bar_glyph(40, 50, 10, use_ascii=False) == " "


def test_bar_glyph_every_eighth():
    # Row V=4, step=1, band [3.5, 4.5). h = 3.5 + k/8 for k=1..8.
    expected = "▁▂▃▄▅▆▇█"
    for k, ch in enumerate(expected, start=1):
        h = 3.5 + k / 8
        assert _bar_glyph(h, 4, 1, use_ascii=False) == ch, (k, h)


def test_bar_glyph_ascii_collapses_to_one_fill():
    assert _bar_glyph(40, 40, 10, use_ascii=True) == "#"
    assert _bar_glyph(40, 30, 10, use_ascii=True) == "#"
    assert _bar_glyph(40, 50, 10, use_ascii=True) == " "


# ---------------------------------------------------------------------------
# Line-dataset edge cases: axis baseline points and non-adjacent runs
# ---------------------------------------------------------------------------


def test_snap_to_row_baseline_snaps_to_y_min_when_included_in_levels():
    # step=10, rows [90, 80, 70, ..., 10]; y_min=0 appended as render() does
    # for a line dataset -- a value resting on the baseline must snap to
    # y_min itself, not fall through to None (the old bug: y_min was never
    # in `levels`, so its band [-5, 5) matched nothing).
    levels = [*(90 - 10 * i for i in range(9)), 0]
    assert _snap_to_row(0, 10, levels) == 0
    assert _snap_to_row(3, 10, levels) == 0


def test_line_point_at_axis_baseline_connects_instead_of_vanishing():
    chart = parse(
        "xychart-beta\n    x-axis [Q1, Q2, Q3, Q4]\n    y-axis 0 --> 100\n"
        "    line [0, 50, 100, 50]\n"
    )
    out = render(chart, width=60)
    # Q1's point (0, the axis minimum) must leave a glyph on the bottom axis
    # row -- the old bug snapped it to None and dropped it with no trace.
    bottom_axis = next(line for line in out.splitlines() if "└" in line)
    plot = bottom_axis.split("└", 1)[1]
    assert any(ch in plot for ch in "╭╮╰╯│"), f"no line glyph on baseline row: {bottom_axis!r}"


def test_build_line_grid_run_with_no_predecessor_does_not_wrap_to_last_run():
    # Regression for `runs[ridx - 1]` reading `runs[-1]` via Python's
    # negative-index wraparound when the first run has no real predecessor
    # (here: category 0's value snaps to None, so the run starting at
    # category 1 is not adjacent to anything and must not be connected to
    # the last run in the list).
    levels = [80.0, 60.0, 40.0, 20.0]
    step = 20.0
    # None, 40, 80, 20 -- category 0 has no snapped value (simulates an
    # out-of-range point); category 3's value (20) is far from category
    # 1's (40) and must never appear connected to it.
    values = [-1000.0, 40.0, 80.0, 20.0]
    grid = _build_line_grid(values, levels, step, col_width=4, g=_UNICODE)
    # The old bug drew a "│" connecting category 1's run down/up towards
    # category 3's value (20) at category 1's leading column, spanning
    # every row strictly between 40 and 20.
    leading_col = 1 * 4  # category index 1's first column
    assert grid[20.0][leading_col] == " "


# ---------------------------------------------------------------------------
# Nice tick spacing (y-axis labels land on round numbers, not an arbitrary
# fraction of the axis range divided by _plot_geometry's row count)
# ---------------------------------------------------------------------------


def test_nice_step_snaps_to_one_two_five_or_ten():
    assert _nice_step(6) == 5      # 120/20, the motivating case
    assert _nice_step(0.04) == 0.05
    assert _nice_step(3.2) == 5
    assert _nice_step(1.4) == 1
    assert _nice_step(2.4) == 2
    assert _nice_step(90) == 100
    assert _nice_step(5) == 5      # already nice: unchanged


def test_y_axis_ticks_are_whole_or_five_ten_intervals():
    # y-axis 0-->120 at a width whose raw row count doesn't divide 120
    # evenly (the motivating report: ticks like 4.8/9.6/... instead of
    # round numbers) must produce ticks that are all whole numbers, each a
    # consistent step apart, snapped to a 1/2/5 x 10^k spacing.
    chart = parse(
        "xychart-beta\n    x-axis [Q1, Q2, Q3, Q4]\n    y-axis 0 --> 120\n"
        "    bar [40, 60, 80, 100]\n"
    )
    out = render(chart, width=100)
    ticks = [
        float(line.split("│", 1)[0].strip())
        for line in out.splitlines()
        if "│" in line
    ]
    assert all(t == int(t) for t in ticks), ticks
    steps = {round(a - b, 6) for a, b in zip(ticks, ticks[1:], strict=False)}
    assert steps == {5.0} or steps == {10.0} or steps == {2.0} or steps == {1.0}, steps


# ---------------------------------------------------------------------------
# Golden fixtures
# ---------------------------------------------------------------------------


def _golden_cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        expected = mmd.with_suffix(".out")
        if expected.exists():
            yield pytest.param(mmd, expected, id=mmd.stem)


@pytest.mark.parametrize("mmd_path,expected_path", list(_golden_cases()))
def test_matches_fixture(mmd_path, expected_path):
    chart = parse(mmd_path.read_text())
    width = 100 if mmd_path.stem == "nvda" else 80
    # color=True coverage lives in test_color_true_strips_to_the_same_plain_text_as_fixtures --
    # asserting it here too against the same fixtures would just re-run the identical comparison.
    assert render(chart, use_ascii=False, width=width) == expected_path.read_text()


def test_tick_aligned_bar_renders_half_block():
    # y 0-->10 with W=20 (cell-aspect-corrected floor) yields n_rows=5,
    # step=2, so 4 is an exact tick.
    chart = parse("xychart-beta\n    x-axis [A]\n    y-axis 0 --> 10\n    bar [4]\n")
    out = render(chart, use_ascii=False, width=20)
    row = _row_for_tick(out, "4")
    assert "▄" in row
    assert "█" not in row.split("│", 1)[1]


def test_eighth_block_levels_all_appear_in_a_render():
    # 8 categories, W=32 (cell-aspect-corrected floor) -> plot_w=16,
    # n_rows=8, step=1 for y 0-->8. Bars land at 3.5+k/8 so row 4 shows
    # every eighth glyph.
    cats = ",".join("ABCDEFGH")
    vals = ",".join(str(3.5 + k / 8) for k in range(1, 9))
    chart = parse(
        f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 8\n    bar [{vals}]\n"
    )
    out = render(chart, use_ascii=False, width=32)
    row = _row_for_tick(out, "4")
    plot = row.split("│", 1)[1]
    for ch in "▁▂▃▄▅▆▇█":
        assert ch in plot, f"missing {ch!r} in {plot!r}\n{out}"


# ---------------------------------------------------------------------------
# Requirement 8: plot area scales with caller-supplied width
# ---------------------------------------------------------------------------


_SALES = (
    "xychart-beta\n"
    '    title "Sales"\n'
    "    x-axis [Q1, Q2, Q3, Q4]\n"
    "    y-axis 0 --> 100\n"
    "    bar [40, 55, 70, 90]\n"
)


def test_plot_width_at_fifty_percent_floor():
    # 4 short categories: content min is well below 50% of W=80, so the
    # plot sits on the floor (40 columns) with height corrected for the
    # terminal cell's ~2:1 aspect so it looks square, not literal 1:1 in
    # raw row/column counts (which would render twice as tall as wide).
    chart = parse(_SALES)
    out = render(chart, use_ascii=False, width=80)
    pw = _inner_plot_width(out)
    ph = _plot_height(out)
    assert pw == 40
    assert ph == 20
    # Must not compress narrower than the floor.
    assert pw >= 40


def test_plot_width_at_one_hundred_percent_cap():
    # 10 one-char categories, content min 20. W=20 puts the plot on the
    # 100% ceiling; it must not grow past it. y-axis 0-->10 is chosen so
    # its nice-step-adjusted row count (see _nice_step) lands exactly on
    # _plot_geometry's own target (5 rows), keeping this test focused on
    # width/aspect geometry rather than tick-spacing rounding.
    cats = ",".join(f"{i}" for i in range(10))
    vals = ",".join("1" for _ in range(10))
    chart = parse(f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 10\n    bar [{vals}]\n")
    out = render(chart, use_ascii=False, width=20)
    pw = _inner_plot_width(out)
    ph = _plot_height(out)
    assert pw == 20
    assert ph == 5  # 2:1 at the ceiling, visually (cell-aspect corrected)
    assert pw <= 20


def test_plot_height_grows_slower_than_width_between_bounds():
    # W=30, 10 one-char cats, content=20: between floor 15 and ceil 30.
    # y-axis 0-->70 lands its nice step exactly on _plot_geometry's target
    # (7 rows), same reasoning as the ceiling test above.
    cats = ",".join(f"{i}" for i in range(10))
    vals = ",".join("1" for _ in range(10))
    chart = parse(f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 70\n    bar [{vals}]\n")
    out = render(chart, use_ascii=False, width=30)
    pw = _inner_plot_width(out)
    ph = _plot_height(out)
    assert pw == 20
    assert ph == 7  # frozen at the 50%-of-W floor, so height < width
    assert pw / ph <= 2.0 * 2 + 1e-9  # visual 2:1 == raw 4:1 (cell-aspect)


def test_plot_overflows_when_fifty_percent_floor_cannot_fit_labels():
    # 10 long labels, min_col ~ 10, content ~ 100. W=20 cannot hold them
    # even at 100%, so the plot overflows and scrolls (VIEWMD-0018).
    cats = ",".join(f"Category{i}" for i in range(10))
    vals = ",".join("1" for _ in range(10))
    chart = parse(f"xychart-beta\n    x-axis [{cats}]\n    bar [{vals}]\n")
    out = render(chart, use_ascii=False, width=20)
    pw = _inner_plot_width(out)
    assert pw > 20


def test_plot_geometry_unit():
    # Directly pins the three requirement-8 bounds, corrected for the
    # terminal cell's own ~2:1 (tall:wide) aspect (_CELL_ASPECT) so the
    # ratios hold visually rather than in raw column/row counts.
    col, pw, rows = _plot_geometry(4, 3, 80)
    assert pw == 40 and rows == 20 and col == 10  # visually ~1:1 at the floor
    col, pw, rows = _plot_geometry(10, 2, 20)
    assert pw == 20 and rows == 5 and col == 2  # visually 2:1 at the ceiling
    col, pw, rows = _plot_geometry(10, 2, 30)
    assert pw == 20 and rows == 7 and col == 2
    # Snapping to whole columns must not drop back below the 50% floor.
    col, pw, rows = _plot_geometry(13, 6, 200)
    assert pw >= 100
    assert pw <= 200


def test_cli_width_reaches_the_renderer():
    # Same plumbing regression pie/quadrant already pin: `width` must not
    # be dropped in favour of a freshly-queried terminal size.
    md = f"```mermaid\n{_SALES}```\n"
    narrow = render_markdown(md, width=40, color=False)
    wide = render_markdown(md, width=80, color=False)
    assert narrow != wide


# ---------------------------------------------------------------------------
# use_ascii fallback (requirement 7)
# ---------------------------------------------------------------------------


def test_ascii_mode_collapses_bar_and_line_glyphs():
    chart = parse(
        "xychart-beta\n"
        "    x-axis [Q1, Q2, Q3, Q4]\n"
        "    y-axis 0 --> 100\n"
        "    bar  [40, 60, 80, 100]\n"
        "    line [60, 80, 100, 120]\n"
    )
    out = render(chart, use_ascii=True, width=80)
    for ch in "█▁▂▃▄▅▆▇╭╮╰╯│─└┬":
        assert ch not in out
    assert "#" in out
    assert "+" in out
    assert "-" in out
    assert "|" in out


# ---------------------------------------------------------------------------
# Dispatch / fallback (requirement 9 and unsupported multi-series)
# ---------------------------------------------------------------------------


def test_xychart_fence_is_recognized_end_to_end():
    text = "```mermaid\n" + _SALES + "```\n"
    got = render_mermaid_blocks(text, width=80)
    assert "```mermaid\n" not in got
    assert f"```{MERMAID_RENDERED_INFO}\n" in got
    assert "Sales" in got
    assert "│" in got


def test_bare_xychart_fence_is_recognized_end_to_end():
    text = "```mermaid\nxychart\n    x-axis [A, B]\n    bar [1, 2]\n```\n"
    got = render_mermaid_blocks(text, width=80)
    assert f"```{MERMAID_RENDERED_INFO}\n" in got


def test_malformed_dataset_length_falls_back_to_raw_fence():
    text = "```mermaid\nxychart-beta\n    x-axis [A, B, C]\n    bar [1, 2]\n```\n"
    assert render_mermaid_blocks(text) == text
    with pytest.raises(mermaid.MermaidError):
        mermaid.render("xychart-beta\n    x-axis [A, B, C]\n    bar [1, 2]\n")


def test_multi_series_falls_back_to_raw_fence():
    text = (
        "```mermaid\n"
        "xychart\n"
        '    title "Different Colors in xyChart"\n'
        '    x-axis "categoriesX" ["Category 1", "Category 2", "Category 3", "Category 4"]\n'
        '    y-axis "valuesY" 0 --> 50\n'
        "    line [10,20,30,40]\n"
        "    bar [20,30,25,35]\n"
        "    bar [15,25,20,30]\n"
        "    line [5,15,25,35]\n"
        "```\n"
    )
    assert render_mermaid_blocks(text) == text


def test_numeric_x_axis_falls_back_to_raw_fence():
    text = "```mermaid\nxychart-beta\n    x-axis 0 --> 10\n    bar [1, 2]\n```\n"
    assert render_mermaid_blocks(text) == text


def test_horizontal_still_renders_bottom_up():
    src = (
        "xychart-beta horizontal\n"
        "    x-axis [Q1, Q2]\n"
        "    y-axis 0 --> 10\n"
        "    bar [4, 8]\n"
    )
    out = render(parse(src), use_ascii=False, width=20)
    # Categories along the bottom, not down the left edge.
    assert out.splitlines()[-1].strip().startswith("Q1")
    assert "Q2" in out.splitlines()[-1]


def test_auto_scale_uses_data_min_max():
    chart = parse("xychart-beta\n    x-axis [A, B]\n    bar [40, 80]\n")
    out = render(chart, use_ascii=False, width=20)
    # Top tick is the data max (or close); bottom is the data min.
    ticks = [ln.split()[0] for ln in out.splitlines() if "│" in ln or "└" in ln]
    assert "80" in ticks[0]
    assert "40" in ticks[-1]


def test_existing_diagram_types_unchanged():
    # Requirement 10: a pie fence still renders as a pie, not an xychart.
    text = '```mermaid\npie\n    "A" : 1\n    "B" : 1\n```\n'
    got = render_mermaid_blocks(text)
    assert "┃" in got
    assert "xychart" not in got


# ---------------------------------------------------------------------------
# Color (VIEWMD-0063): ANSI wrap around already-placed bar/line glyphs
# ---------------------------------------------------------------------------

_LINE_ONLY = (
    "xychart-beta\n"
    '    title "Revenue Trend"\n'
    "    x-axis [Q1, Q2, Q3, Q4]\n"
    "    y-axis 0 --> 100\n"
    "    line [40, 60, 20, 100]\n"
)

_COMBO = (
    "xychart-beta\n"
    '    title "Sales vs Target"\n'
    "    x-axis [Q1, Q2, Q3, Q4]\n"
    "    y-axis 0 --> 120\n"
    "    bar  [40, 60, 80, 100]\n"
    "    line [60, 80, 100, 120]\n"
)


def test_bar_only_dataset_is_colored():
    out = render(parse(_SALES), color=True, width=80)
    for hex_ in _BAR_COLORS[:4]:
        assert _sgr(hex_) in out
    assert _sgr(_LINE_COLOR) not in out
    assert re.search(rf"\x1b\[{_sgr(_BAR_COLORS[0])}m[█▁▂▃▄▅▆▇]+", out)


def test_line_only_dataset_is_colored():
    out = render(parse(_LINE_ONLY), color=True, width=80)
    assert _sgr(_LINE_COLOR) in out
    for hex_ in _BAR_COLORS:
        assert _sgr(hex_) not in out
    assert re.search(rf"\x1b\[{_sgr(_LINE_COLOR)}m[─│╭╮╰╯]+", out)


def test_combo_chart_uses_two_distinct_hues():
    out = render(parse(_COMBO), color=True, width=80)
    assert _sgr(_BAR_COLORS[0]) in out
    assert _sgr(_LINE_COLOR) in out
    assert _LINE_COLOR not in _BAR_COLORS
    assert re.search(rf"\x1b\[{_sgr(_BAR_COLORS[0])}m[█▁▂▃▄▅▆▇]+", out)
    assert re.search(rf"\x1b\[{_sgr(_LINE_COLOR)}m[─│╭╮╰╯]+", out)


def test_axes_title_ticks_and_labels_stay_plain():
    out = render(parse(_COMBO), color=True, width=80)
    lines = out.splitlines()
    assert "Sales vs Target" in lines[0]
    assert "\x1b[" not in lines[0]
    assert "Q1" in lines[-1] and "Q4" in lines[-1]
    assert "\x1b[" not in lines[-1]
    for line in lines:
        if "│" in line:
            # First │ is the y-axis (uncolored); later │ in `plot` are line
            # glyphs and *are* colored -- only the prefix through the axis
            # must stay plain.
            left, _right = line.split("│", 1)
            assert "\x1b[" not in left, line
        if "└" in line:
            assert "\x1b[" not in line.split("└", 1)[0], line
            assert not re.search(r"\x1b\[[0-9;]*m└", line), line
            assert not re.search(r"\x1b\[[0-9;]*m┬", line), line


def test_color_true_strips_to_the_same_plain_text_as_fixtures():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        expected = mmd.with_suffix(".out")
        if not expected.exists():
            continue
        chart = parse(mmd.read_text())
        width = 100 if mmd.stem == "nvda" else 80
        colored = render(chart, color=True, width=width)
        plain = render(chart, color=False, width=width)
        assert plain == expected.read_text()
        assert _strip_ansi(colored) == plain


def test_color_flag_reaches_xychart_through_dispatch_and_markdown():
    md = f"```mermaid\n{_SALES}```\n"
    assert "\x1b[" not in mermaid.render(_SALES, width=80)
    assert "\x1b[38;2;" in mermaid.render(_SALES, color=True, width=80)
    assert "\x1b[" not in render_markdown(md, width=80, color=False)
    assert "\x1b[38;2;" in render_markdown(md, width=80, color=True)


def test_color_and_use_ascii_are_independent():
    out = render(parse(_COMBO), use_ascii=True, color=True, width=80)
    assert "\x1b[38;2;" in out
    for ch in "█▁▂▃▄▅▆▇╭╮╰╯│─└┬":
        assert ch not in out
    assert _sgr(_BAR_COLORS[0]) in out
    assert _sgr(_LINE_COLOR) in out


def test_baseline_line_glyphs_are_colored_axis_ticks_are_not():
    chart = parse(
        "xychart-beta\n    x-axis [Q1, Q2, Q3, Q4]\n    y-axis 0 --> 100\n"
        "    line [0, 50, 100, 50]\n"
    )
    out = render(chart, color=True, width=60)
    axis = next(line for line in out.splitlines() if "└" in line)
    assert not re.search(r"\x1b\[[0-9;]*m└", axis)
    assert _sgr(_LINE_COLOR) in axis
    assert all(_sgr(h) not in axis for h in _BAR_COLORS)


# ---------------------------------------------------------------------------
# Per-bar color and inter-bar gap (VIEWMD-0064)
# ---------------------------------------------------------------------------


def _bar_run_hexes(row: str) -> list[str]:
    """Left-to-right hex colors of bar-glyph SGR runs in a y-axis plot row."""
    plot = row.split("│", 1)[1] if "│" in row else row
    return [
        f"{int(m.group(1)):02x}{int(m.group(2)):02x}{int(m.group(3)):02x}"
        for m in re.finditer(r"\x1b\[38;2;(\d+);(\d+);(\d+)m[█▁▂▃▄▅▆▇#]+", plot)
    ]


def _plot_rows(out: str) -> list[str]:
    rows = []
    for line in out.splitlines():
        if "│" in line:
            rows.append(line.split("│", 1)[1])
    return rows


def test_multi_category_bar_chart_uses_a_different_hex_per_bar():
    out = render(parse(_SALES), color=True, width=80)
    hexes = _bar_run_hexes(_row_for_tick(out, "5"))
    assert hexes == _BAR_COLORS[:4]
    assert len(set(hexes)) == 4


def test_adjacent_bars_never_share_a_color_when_palette_wraps():
    n = len(_BAR_COLORS) + 2
    expected = [_bar_color(i) for i in range(n)]
    for a, b in zip(expected, expected[1:], strict=False):
        assert a != b
    assert _LINE_COLOR not in _BAR_COLORS
    assert len(set(_BAR_COLORS)) == len(_BAR_COLORS)

    col_width = 4
    chars: list[str] = []
    for _i in range(n):
        chars.extend(["█"] * (col_width - _BAR_GAP))
        chars.extend([" "] * _BAR_GAP)
    spans = _plot_color_spans(chars, None, _UNICODE, col_width)
    assert [fg for _s, _e, fg, _bg in spans] == expected

    cats = ",".join(str(i) for i in range(n))
    vals = ",".join("10" for _ in range(n))
    chart = parse(
        f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 10\n    bar [{vals}]\n"
    )
    out = render(chart, color=True, width=80)
    full = next(ln for ln in out.splitlines() if "│" in ln and "█" in _strip_ansi(ln))
    hexes = _bar_run_hexes(full)
    assert hexes == expected
    for a, b in zip(hexes, hexes[1:], strict=False):
        assert a != b


def test_gap_between_adjacent_bars_with_color_on_or_off():
    # The gap sits before every bar except the first (VIEWMD-0064 finding 1
    # fix) -- the first bar has no left neighbor to share a gap with, so it
    # fills its whole column; every later bar leads with one blank column.
    chart = parse(_SALES)
    expected = "█" * 10 + (" " + "█" * 9) * 3
    for color in (False, True):
        out = render(chart, color=color, width=80)
        plot = _strip_ansi(_row_for_tick(out, "5")).split("│", 1)[1]
        assert plot == expected, (color, plot)


def test_minimum_column_still_leaves_a_fillable_bar():
    # 10 one-char categories at W=20 pins col_width=_MIN_COL=2 (requirement 5:
    # 1 fill + 1 gap, never a vanished bar). Gap leads every bar but the
    # first (VIEWMD-0064 finding 1 fix).
    cats = ",".join(str(i) for i in range(10))
    vals = ",".join("10" for _ in range(10))
    chart = parse(
        f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 10\n    bar [{vals}]\n"
    )
    col, _pw, _rows = _plot_geometry(10, 2, 20)
    assert col == 2
    out = render(chart, use_ascii=False, width=20)
    plot = _row_for_tick(out, "2").split("│", 1)[1]
    assert plot == "██" + " █" * 9


def test_single_category_chart_still_renders_a_fillable_bar():
    chart = parse("xychart-beta\n    x-axis [A]\n    y-axis 0 --> 10\n    bar [8]\n")
    out = render(chart, use_ascii=False, width=20)
    plot = _row_for_tick(out, "4").split("│", 1)[1]
    assert any(ch in "█▁▂▃▄▅▆▇" for ch in plot)
    assert plot.strip(" ") != ""


def test_combo_chart_bar_survives_line_peak_at_minimum_column_width():
    # Peer-review finding 1 against VIEWMD-0064: at col_width == _MIN_COL,
    # a bar's one fillable column used to be exactly the column
    # `_build_line_grid` writes a category's own corner/vertical-stem glyph
    # into, so a line peak/trough could erase the bar entirely. Every
    # category here shares the same (max) bar value; an alternating line
    # must not blank out any of them.
    cats = ",".join(str(i) for i in range(10))
    vals = ",".join("10" for _ in range(10))
    line = ",".join("1" if i % 2 == 0 else "10" for i in range(10))
    chart = parse(
        f"xychart-beta\n    x-axis [{cats}]\n    y-axis 0 --> 10\n"
        f"    bar [{vals}]\n    line [{line}]\n"
    )
    col, _pw, _rows = _plot_geometry(10, 2, 20)
    assert col == 2
    out = render(chart, use_ascii=False, width=20)
    plot = _row_for_tick(out, "4").split("│", 1)[1]
    for i in range(10):
        fill_col = 0 if i == 0 else i * col + 1
        assert plot[fill_col] in "█▁▂▃▄▅▆▇", (i, plot)


def test_combo_line_hue_and_position_unchanged():
    line_only = parse(
        "xychart-beta\n    x-axis [Q1, Q2, Q3, Q4]\n    y-axis 0 --> 120\n"
        "    line [60, 80, 100, 120]\n"
    )
    combo_out = render(parse(_COMBO), width=80)
    line_out = render(line_only, width=80)
    line_chars = set("─│╭╮╰╯")
    for lr, cr in zip(_plot_rows(line_out), _plot_rows(combo_out), strict=True):
        assert len(lr) == len(cr)
        for i, ch in enumerate(lr):
            if ch in line_chars:
                assert cr[i] == ch
    colored = render(parse(_COMBO), color=True, width=80)
    assert _sgr(_LINE_COLOR) in colored
    for hex_ in _BAR_COLORS:
        assert hex_ != _LINE_COLOR


def test_line_only_output_matches_pre_gap_fixtures():
    # Requirement 7: a chart with no bar dataset is byte-identical to before
    # this issue. revenue_trend and nvda are line-only; their .out files are
    # the VIEWMD-0063 pin and must not be regenerated.
    for stem, width in (("revenue_trend", 80), ("nvda", 100)):
        mmd = FIXTURES / f"{stem}.mmd"
        expected = FIXTURES / f"{stem}.out"
        assert render(parse(mmd.read_text()), width=width) == expected.read_text()


# ---------------------------------------------------------------------------
# Line-over-bar background fill (VIEWMD-0066)
# ---------------------------------------------------------------------------

# tools/demo-pages/16-xychart.md's own chart: Q3's line value (60) sits inside
# Q3's bar (80), so the line's horizontal run at row 60 rides across the
# bottom of Q3's bar for its full leading span (the motivating report).
_LINE_OVER_BAR = (
    "xychart-beta\n"
    '    title "Sales vs Target"\n'
    "    x-axis [Q1, Q2, Q3, Q4]\n"
    "    y-axis 0 --> 120\n"
    "    bar  [40, 60, 80, 100]\n"
    "    line [60, 80, 60, 120]\n"
)


def test_line_crossing_a_bar_gets_that_bars_color_as_background():
    out = render(parse(_LINE_OVER_BAR), color=True, width=100)
    combined = f"\x1b[{_sgr(_LINE_COLOR)};{_bg_sgr(_bar_color(2))}m"
    assert combined in out


def test_line_not_crossing_a_bar_keeps_foreground_only_no_background():
    # The riser between Q1 and Q2 (gap column, VIEWMD-0064) has no bar fill
    # under it at any row -- must stay exactly as VIEWMD-0063 shipped it.
    out = render(parse(_LINE_OVER_BAR), color=True, width=100)
    plain_line = re.compile(rf"\x1b\[{re.escape(_sgr(_LINE_COLOR))}m")
    assert plain_line.search(out)
    combined = re.compile(rf"\x1b\[{re.escape(_sgr(_LINE_COLOR))};48;2;\d+;\d+;\d+m")
    assert combined.search(out)  # the Q3 crossing is still present elsewhere in this chart


def test_line_only_chart_never_gets_a_background():
    out = render(parse(_LINE_ONLY), color=True, width=80)
    assert "48;2;" not in out


def test_bar_cell_the_line_never_touches_keeps_foreground_only():
    # Q1's bar (height 40) never has the line over it in _LINE_OVER_BAR (the
    # line stays at or above 60 throughout) -- its color must stay exactly
    # as VIEWMD-0064 shipped it, no background added.
    out = render(parse(_LINE_OVER_BAR), color=True, width=100)
    q1_only = re.compile(rf"\x1b\[{re.escape(_sgr(_bar_color(0)))}m[█▁▂▃▄▅▆▇]+\x1b\[0m")
    assert q1_only.search(out)
    combined_q1 = re.compile(rf"\x1b\[{re.escape(_sgr(_bar_color(0)))};48;2;")
    assert not combined_q1.search(out)


def test_color_off_output_unaffected_by_line_over_bar():
    out = render(parse(_LINE_OVER_BAR), color=False, width=100)
    assert "\x1b[" not in out


def test_bar_only_chart_unaffected_by_line_over_bar_change():
    out = render(parse(_SALES), color=True, width=80)
    assert "48;2;" not in out
