"""Golden-file regression tests for the flowchart port (VIEWMD-0015).

Fixtures in tests/fixtures/mermaid_flowchart/ were originally generated by
running each `<name>.mmd` through the upstream Go reference implementation
(github.com/AlexanderGrooff/mermaid-ascii, MIT licensed) with and without
`--ascii`, saving its stdout as `<name>.unicode.out` / `<name>.ascii.out`.

Since VIEWMD-0036, every node box (rectangle and the VIEWMD-0022 shapes alike)
deliberately diverges from that reference by omitting the blank interior row
above/below a single- or multi-line label -- verified by hand-diffing each
fixture against its pre-VIEWMD-0036 version to confirm only those padding
rows were removed, nothing else. Fixtures are otherwise still byte-for-byte
faithful to the reference implementation.

Fixtures that exercise non-rectangle node shapes (`shapes_fallback`,
`complex_backend`, `shape_*`) are hand-authored VIEWMD-0022 divergences --
upstream has no reference output for those shapes -- and are visually verified
rather than differentially tested.
"""

from pathlib import Path

import pytest

from viewmd.mermaid.flowchart.parser import parse
from viewmd.mermaid.flowchart.renderer import render

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_flowchart"


def _cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        for variant, use_ascii in (("unicode", False), ("ascii", True)):
            expected = mmd.with_name(f"{mmd.stem}.{variant}.out")
            if expected.exists():
                yield pytest.param(mmd, expected, use_ascii, id=f"{mmd.stem}-{variant}")


@pytest.mark.parametrize("mmd_path,expected_path,use_ascii", list(_cases()))
def test_matches_reference_implementation(mmd_path, expected_path, use_ascii):
    properties = parse(mmd_path.read_text())
    assert render(properties, use_ascii=use_ascii) == expected_path.read_text()


def test_diamond_chain_arrows_land_flush_on_both_sides():
    """Two diamonds in a row (VIEWMD-0038) must both attach flush -- the
    connector lands directly on the neighbouring diamond's `◇` marker with
    no gap in between."""
    properties = parse(
        "graph LR\n    S{OK} --> M{Decide}\n    M --> L{Continue?}\n"
    )
    out = render(properties, use_ascii=False)
    lines = out.splitlines()
    mid_line = next(line for line in lines if "OK" in line)
    assert "──►◇" in mid_line
    assert "──► ◇" not in mid_line


def test_diamond_height_independent_of_sibling_column_width():
    """A diamond sharing a TD grid column with a much wider rectangle sibling
    (here `Handle left`) must still render at exactly `label_lines + 2` rows
    -- VIEWMD-0038 req. 2's decoupling: unlike the old tapered rhombus, a
    diamond's height never depends on its own or a sibling's width."""
    properties = parse(
        "graph TD\n"
        "    A([Begin]) --> B{Path?}\n"
        "    B -->|left| C[Handle left]\n"
        "    B -->|right| D[Handle right]\n"
        "    C --> E([End])\n"
        "    D --> E\n"
    )
    out = render(properties, use_ascii=False)
    lines = out.splitlines()
    diamond_lines = [i for i, line in enumerate(lines) if "◇" in line]
    assert diamond_lines == [diamond_lines[0], diamond_lines[0] + 1, diamond_lines[0] + 2]
    assert "Path?" in lines[diamond_lines[0] + 1]


def test_vertical_edge_label_does_not_widen_plain_rectangle_nodes():
    """A labelled vertical edge between two bare `[...]` nodes must not widen
    the nodes -- that's VIEWMD-0015's byte-for-byte baseline, unaffected by
    VIEWMD-0022's horizontal edge-label padding (regression: the padding
    formula was briefly applied to vertical labels too, widening
    `bidirectional`'s Client/Server boxes from 8 to 10 columns)."""
    properties = parse("graph TD\n  A[Client] <-->|sync| B[Server]\n")
    out = render(properties, use_ascii=False)
    assert "┌────────┐" in out
    assert "┌──────────┐" not in out
