"""Golden-file regression tests for the flowchart port (VIEWMD-0015).

Fixtures in tests/fixtures/mermaid_flowchart/ were originally generated by
running each `<name>.mmd` through the upstream Go reference implementation
(github.com/AlexanderGrooff/mermaid-ascii, MIT licensed) with and without
`--ascii`, saving its stdout as `<name>.unicode.out` / `<name>.ascii.out`.
Rectangle-only fixtures still pin this port byte-for-byte to that reference.

Fixtures that exercise non-rectangle node shapes (`shapes_fallback`,
`complex_backend`, `shape_*`) are hand-authored VIEWMD-0022 divergences --
upstream has no reference output for those shapes -- and are visually verified
rather than differentially tested.
"""

from pathlib import Path

import pytest

from viewmd.mermaid.flowchart.parser import parse
from viewmd.mermaid.flowchart.renderer import render

FIXTURES = Path(__file__).parent / "fixtures" / "mermaid_flowchart"


def _cases():
    for mmd in sorted(FIXTURES.glob("*.mmd")):
        for variant, use_ascii in (("unicode", False), ("ascii", True)):
            expected = mmd.with_name(f"{mmd.stem}.{variant}.out")
            if expected.exists():
                yield pytest.param(mmd, expected, use_ascii, id=f"{mmd.stem}-{variant}")


@pytest.mark.parametrize("mmd_path,expected_path,use_ascii", list(_cases()))
def test_matches_reference_implementation(mmd_path, expected_path, use_ascii):
    properties = parse(mmd_path.read_text())
    assert render(properties, use_ascii=use_ascii) == expected_path.read_text()
