#compdef viewmd
# Generated by ./tools.sh completions from viewmd's argparse parser -- do not hand-edit.
# Install: place (or symlink) this file as `_viewmd` in a directory on your $fpath, e.g.
# `~/.zsh/completions/_viewmd`, then `autoload -Uz compinit && compinit` (or restart your shell).

_viewmd() {
  _arguments \
  "-h[-h/--help]" \
  "--help[-h/--help]" \
  "--version[--version]" \
  "--no-pager[--no-pager]" \
  "--color[--color]:value:(auto always never)" \
  "--width[--width]:value:(full)" \
  "--full-front-matter[--full-front-matter/--no-full-front-matter]" \
  "--no-full-front-matter[--full-front-matter/--no-full-front-matter]" \
  "--toc[--toc/--no-toc]" \
  "--no-toc[--toc/--no-toc]" \
  "--config[--config]:path:_files" \
  '*:path:_files'
}

_viewmd "$@"
