# Generated by ./tools.sh completions from viewmd's argparse parser -- do not hand-edit.
# Install: copy or symlink this file to `~/.config/fish/completions/viewmd.fish`
# (or any directory on $fish_complete_path), then start a new fish shell.

# Positional path arguments: plain filesystem completion, no extension filter -- any file or
# directory is valid, viewmd reads '-' for stdin too.
complete -c viewmd -f -a '(__fish_complete_path)'

complete -c viewmd -s h
complete -c viewmd -l help
complete -c viewmd -l version
complete -c viewmd -l no-pager
complete -c viewmd -l color -xa 'auto always never'
complete -c viewmd -l width -xa 'full'
complete -c viewmd -l theme -xa 'dark light'
complete -c viewmd -l full-front-matter
complete -c viewmd -l no-full-front-matter
complete -c viewmd -l toc
complete -c viewmd -l no-toc
complete -c viewmd -l depth -rF
complete -c viewmd -l config -rF
