# Generated by ./tools.sh completions from viewmd's argparse parser -- do not hand-edit.
# Install: source this file, e.g. `source completions/viewmd.bash` (or copy/symlink it into a
# directory your bash-completion setup sources, such as /etc/bash_completion.d/ or
# $(brew --prefix)/etc/bash_completion.d/ on Homebrew).

_viewmd_completions() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMPREPLY=()

    case "$prev" in
        --color) COMPREPLY=($(compgen -W "auto always never" -- "$cur")); return ;;
        --width) COMPREPLY=($(compgen -W "full" -- "$cur")); return ;;
        --theme) COMPREPLY=($(compgen -W "dark light" -- "$cur")); return ;;
        --depth) COMPREPLY=($(compgen -f -- "$cur")); return ;;
        --config) COMPREPLY=($(compgen -f -- "$cur")); return ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "-h --help --version --no-pager --color --width --theme --full-front-matter --no-full-front-matter --toc --no-toc --depth --config" -- "$cur"))
        return
    fi

    COMPREPLY=($(compgen -f -- "$cur"))
}
complete -F _viewmd_completions viewmd
