#!/usr/bin/env python3
"""Generate bash/zsh/fish completion scripts from viewmd's argparse parser.

    python tools/completions.py            # regenerate completions/viewmd.{bash,zsh,fish}
    python tools/completions.py --check    # assert the checked-in scripts are current; write
                                            # nothing

Reads `viewmd.__main__.build_parser()` -- the exact `ArgumentParser` `viewmd`'s CLI parses with
-- via `argparse` introspection (`parser._actions`), so the flag list here can never drift from
a hand-maintained duplicate (VIEWMD-0087 requirement 1). This intentionally does not depend on
`argcomplete`: viewmd's only runtime deps are `rich`/`wcwidth` (AGENTS.md), and completion only
needs a few dozen lines of static-script generation, not a new runtime dependency wired into
`viewmd/__main__.py` itself. The three scripts this emits are plain, dependency-free bash/zsh/fish
functions, checked into `completions/` and regenerated here whenever a flag changes.

Not part of the viewmd package and not imported by it.
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
COMPLETIONS_DIR = ROOT / "completions"

sys.path.insert(0, str(ROOT))
from viewmd.__main__ import build_parser  # noqa: E402


def _option_specs(parser: argparse.ArgumentParser) -> list[dict]:
    """Extracts each optional flag's completion-relevant shape from the parser's own actions.

    Returns one dict per action carrying at least one `--flag` option string:
      - `options`: every spelling for the action (e.g. `["--toc", "--no-toc"]` for a
        `BooleanOptionalAction` pair -- argparse itself expands the negated form into the same
        action's `option_strings`, so no extra bookkeeping is needed to catch it).
      - `takes_value`: whether the flag consumes a following argument.
      - `choices`: literal values to offer for that argument, or `None`.
      - `is_path`: whether the argument should fall back to filesystem-path completion.
    """
    specs = []
    for action in parser._actions:
        if not action.option_strings:
            continue  # positional (the `path` argument), handled separately
        if isinstance(action, argparse._VersionAction | argparse._HelpAction):
            specs.append({"options": action.option_strings, "takes_value": False,
                          "choices": None, "is_path": False})
        elif isinstance(action, argparse.BooleanOptionalAction | argparse._StoreTrueAction):
            specs.append({"options": action.option_strings, "takes_value": False,
                          "choices": None, "is_path": False})
        elif action.dest == "width":
            # Numeric widths can't be enumerated, but the literal 'full' can (VIEWMD-0087
            # requirement 2) -- _width_arg's type function has no `choices` argparse can read.
            specs.append({"options": action.option_strings, "takes_value": True,
                          "choices": ["full"], "is_path": False})
        elif action.choices:
            specs.append({"options": action.option_strings, "takes_value": True,
                          "choices": list(action.choices), "is_path": False})
        else:
            # --config PATH: filesystem-path completion, no extension filter.
            specs.append({"options": action.option_strings, "takes_value": True,
                          "choices": None, "is_path": True})
    return specs


def _all_flags(specs: list[dict]) -> list[str]:
    flags = []
    for spec in specs:
        flags.extend(spec["options"])
    return flags


GENERATED_HEADER = (
    "# Generated by ./tools.sh completions from viewmd's argparse parser -- do not hand-edit."
)


def render_bash(specs: list[dict]) -> str:
    flags = " ".join(_all_flags(specs))
    value_cases = []
    for spec in specs:
        if not spec["takes_value"]:
            continue
        pattern = "|".join(spec["options"])
        if spec["choices"]:
            words = " ".join(spec["choices"])
            value_cases.append(
                f'        {pattern}) COMPREPLY=($(compgen -W "{words}" -- "$cur")); return ;;'
            )
        else:  # path completion
            value_cases.append(
                f'        {pattern}) COMPREPLY=($(compgen -f -- "$cur")); return ;;'
            )
    cases = "\n".join(value_cases)
    return f"""{GENERATED_HEADER}
# Install: source this file, e.g. `source completions/viewmd.bash` (or copy/symlink it into a
# directory your bash-completion setup sources, such as /etc/bash_completion.d/ or
# $(brew --prefix)/etc/bash_completion.d/ on Homebrew).

_viewmd_completions() {{
    local cur prev
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    COMPREPLY=()

    case "$prev" in
{cases}
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "{flags}" -- "$cur"))
        return
    fi

    COMPREPLY=($(compgen -f -- "$cur"))
}}
complete -F _viewmd_completions viewmd
"""


def render_zsh(specs: list[dict]) -> str:
    lines = []
    for spec in specs:
        opts = spec["options"]
        opt_desc = "/".join(opts)
        if not spec["takes_value"]:
            for opt in opts:
                lines.append(f'  "{opt}[{opt_desc}]"')
            continue
        if spec["choices"]:
            action_str = "(" + " ".join(spec["choices"]) + ")"
            for opt in opts:
                lines.append(f'  "{opt}[{opt_desc}]:value:{action_str}"')
        else:  # path completion
            for opt in opts:
                lines.append(f'  "{opt}[{opt_desc}]:path:_files"')
    lines.append("  '*:path:_files'")
    args_block = " \\\n".join(lines)
    return f"""#compdef viewmd
{GENERATED_HEADER}
# Install: place (or symlink) this file as `_viewmd` in a directory on your $fpath, e.g.
# `~/.zsh/completions/_viewmd`, then `autoload -Uz compinit && compinit` (or restart your shell).

_viewmd() {{
  _arguments \\
{args_block}
}}

_viewmd "$@"
"""


def render_fish(specs: list[dict]) -> str:
    lines = []
    for spec in specs:
        for opt in spec["options"]:
            # A single leading '-' is a short option (fish's -s), '--' a long one (fish's -l).
            flag = "-s " + opt[1:] if not opt.startswith("--") else "-l " + opt[2:]
            parts = [f"complete -c viewmd {flag}"]
            if spec["choices"]:
                words = " ".join(spec["choices"])
                parts.append(f"-xa '{words}'")
            elif spec["is_path"]:
                parts.append("-rF")
            lines.append(" ".join(parts))
    flag_lines = "\n".join(lines)
    return f"""{GENERATED_HEADER}
# Install: copy or symlink this file to `~/.config/fish/completions/viewmd.fish`
# (or any directory on $fish_complete_path), then start a new fish shell.

# Positional path arguments: plain filesystem completion, no extension filter -- any file or
# directory is valid, viewmd reads '-' for stdin too.
complete -c viewmd -f -a '(__fish_complete_path)'

{flag_lines}
"""


def generate(parser: argparse.ArgumentParser) -> dict[str, str]:
    specs = _option_specs(parser)
    return {
        "viewmd.bash": render_bash(specs),
        "viewmd.zsh": render_zsh(specs),
        "viewmd.fish": render_fish(specs),
    }


def main(argv: list[str] | None = None) -> int:
    arg_parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    arg_parser.add_argument("--check", action="store_true",
                            help="assert the checked-in scripts are current; write nothing")
    args = arg_parser.parse_args(argv)

    generated = generate(build_parser())

    if args.check:
        problems = []
        for name, content in generated.items():
            path = COMPLETIONS_DIR / name
            if not path.exists():
                problems.append(f"completions: {path} does not exist; run ./tools.sh completions")
                continue
            if path.read_text() != content:
                problems.append(f"completions: {path} is stale; run ./tools.sh completions")
        if problems:
            for p in problems:
                print(p, file=sys.stderr)
            return 1
        print("completions: up to date")
        return 0

    COMPLETIONS_DIR.mkdir(exist_ok=True)
    for name, content in generated.items():
        (COMPLETIONS_DIR / name).write_text(content)
    print(f"completions: wrote {', '.join(generated)} to {COMPLETIONS_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
